### ISSUE TITLE
about dataset structured

### ISSUE THREAD

**Issue by ck-w-0** [huangxx156/VADNet#1]
FileNotFoundError: [Errno 2] No such file or directory: './dataset/test/abnorm/.ipynb_checkpoints'
Can the complete contents of dataset be uploaded?
thx!

**Comment by huangxx156** [comment]
Thank you for appreciating our work and you can download the test set we uploaded.

**Comment by 1s3ss** [comment]
> 感谢您对我们的工作的赞赏，您可以下载我们上传的测试集。
![@CE{VN$ (T4(HW4OWQYM(3Q](https://github.com/huangxx156/VADNet/assets/142778579/322fc195-2521-4bde-a903-38ebf7e0fb54)
Hello, when I use the test set you uploaded, and when I run the test.py file, I get the above error, how can I fix it?Thanks！
